version: 1.0.{build}
cache:
- packages -> PocDeploy\packages.config
- PocDeploy\node_modules -> PocDeploy\package.json
- PocDeploy\bower_components -> PocDeploy\bower.json

build_script:
- build-appveyor.cmd

build:
  publish_wap: true
  verbosity: minimal

artifacts:
  - path: artifacts\*.zip

deploy:
- provider: Environment
  name: PocDeploy